/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NodeFilters = string[];

export interface K3DSimpleConfigV1Alpha5 {
	apiVersion: "k3d.io/v1alpha5";
	kind: "Simple";
	metadata?: {
		/**
		 * Name of the cluster (must be a valid hostname and will be prefixed with 'k3d-'). Example: 'mycluster'.
		 */
		name?: string;
	};
	servers?: number;
	agents?: number;
	kubeAPI?: {
		host?: string;
		hostIP?: string;
		hostPort?: string;
	};
	image?: string;
	network?: string;
	subnet?: string;
	token?: string;
	volumes?: {
		volume?: string;
		nodeFilters?: NodeFilters;
	}[];
	ports?: {
		port?: string;
		nodeFilters?: NodeFilters;
	}[];
	files?: {
		source: string;
		destination: string;
		description?: string;
		nodeFilters?: NodeFilters;
	}[];
	options?: {
		k3d?: {
			wait?: boolean;
			timeout?: {
				[k: string]: unknown;
			};
			disableLoadbalancer?: boolean;
			disableImageVolume?: boolean;
			disableRollback?: boolean;
			loadbalancer?: {
				configOverrides?: unknown[];
			};
		};
		k3s?: {
			extraArgs?: {
				arg?: string;
				nodeFilters?: NodeFilters;
			}[];
			nodeLabels?: {
				label?: string;
				nodeFilters?: NodeFilters;
			}[];
		};
		kubeconfig?: {
			updateDefaultKubeconfig?: boolean;
			switchCurrentContext?: boolean;
		};
		runtime?: {
			gpuRequest?: string;
			serversMemory?: string;
			agentsMemory?: string;
			hostPidMode?: boolean;
			labels?: {
				label?: string;
				nodeFilters?: NodeFilters;
			}[];
			ulimits?: {
				name?: string;
				soft?: number;
				hard?: number;
			}[];
			[k: string]: unknown;
		};
	};
	env?: {
		envVar?: string;
		nodeFilters?: NodeFilters;
	}[];
	registries?: {
		/**
		 * Create a new container image registry alongside the cluster.
		 */
		create?: {
			name?: string;
			host?: string;
			hostPort?: string;
			image?: string;
			proxy?: {
				remoteURL?: string;
				username?: string;
				password?: string;
			};
			volumes?: string[];
			enforcePortMatch?: boolean;
		};
		/**
		 * Connect another container image registry to the cluster.
		 */
		use?: string[];
		/**
		 * Reference a K3s registry configuration file or at it's contents here.
		 */
		config?: string;
		additionalProperties?: never;
		[k: string]: unknown;
	};
	/**
	 * Additional IP to multiple hostnames mappings
	 */
	hostAliases?: {
		ip?: string;
		hostnames?: string[];
		[k: string]: unknown;
	}[];
}
